require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SwitchesController do

  # This should return the minimal set of attributes required to create a valid
  # Switch. As you add validations to Switch, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all switches as @switches" do
      switch = Switch.create! valid_attributes
      get :index
      assigns(:switches).should eq([switch])
    end
  end

  describe "GET show" do
    it "assigns the requested switch as @switch" do
      switch = Switch.create! valid_attributes
      get :show, :id => switch.id
      assigns(:switch).should eq(switch)
    end
  end

  describe "GET new" do
    it "assigns a new switch as @switch" do
      get :new
      assigns(:switch).should be_a_new(Switch)
    end
  end

  describe "GET edit" do
    it "assigns the requested switch as @switch" do
      switch = Switch.create! valid_attributes
      get :edit, :id => switch.id
      assigns(:switch).should eq(switch)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Switch" do
        expect {
          post :create, :switch => valid_attributes
        }.to change(Switch, :count).by(1)
      end

      it "assigns a newly created switch as @switch" do
        post :create, :switch => valid_attributes
        assigns(:switch).should be_a(Switch)
        assigns(:switch).should be_persisted
      end

      it "redirects to the created switch" do
        post :create, :switch => valid_attributes
        response.should redirect_to(Switch.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved switch as @switch" do
        # Trigger the behavior that occurs when invalid params are submitted
        Switch.any_instance.stub(:save).and_return(false)
        post :create, :switch => {}
        assigns(:switch).should be_a_new(Switch)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Switch.any_instance.stub(:save).and_return(false)
        post :create, :switch => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested switch" do
        switch = Switch.create! valid_attributes
        # Assuming there are no other switches in the database, this
        # specifies that the Switch created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Switch.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => switch.id, :switch => {'these' => 'params'}
      end

      it "assigns the requested switch as @switch" do
        switch = Switch.create! valid_attributes
        put :update, :id => switch.id, :switch => valid_attributes
        assigns(:switch).should eq(switch)
      end

      it "redirects to the switch" do
        switch = Switch.create! valid_attributes
        put :update, :id => switch.id, :switch => valid_attributes
        response.should redirect_to(switch)
      end
    end

    describe "with invalid params" do
      it "assigns the switch as @switch" do
        switch = Switch.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Switch.any_instance.stub(:save).and_return(false)
        put :update, :id => switch.id, :switch => {}
        assigns(:switch).should eq(switch)
      end

      it "re-renders the 'edit' template" do
        switch = Switch.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Switch.any_instance.stub(:save).and_return(false)
        put :update, :id => switch.id, :switch => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested switch" do
      switch = Switch.create! valid_attributes
      expect {
        delete :destroy, :id => switch.id
      }.to change(Switch, :count).by(-1)
    end

    it "redirects to the switches list" do
      switch = Switch.create! valid_attributes
      delete :destroy, :id => switch.id
      response.should redirect_to(switches_url)
    end
  end

end
